CREATE #PENCILS 4 CELLS ALLOT
0 CONSTANT RED
1 CONSTANT BLUE
2 CONSTANT GREEN
3 CONSTANT ORANGE

: PENCILS   ( color -- addr ) CELLS #PENCILS + ;

23 RED PENCILS !
15 BLUE PENCILS !
12 GREEN PENCILS !
0 ORANGE PENCILS !
